name: flexible_grid_view_plus
description: Flexible grid view is a Flutter package that simplifies the process of creating a grid view. With FlexibleGridView, you don't need to specify the height of your children widgets.
version: 1.2.0
repository: https://github.com/marmelad52/flexible_grid_view_plus

homepage:
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
